In [1]:
import yaml
# import boto3
import pandas as pd
import re
import numpy as np
import sys
import logging 
import sqlalchemy

In [2]:
from load_creds_file import *
from postgres_functions import *
from etl_functions import *

load creds script run
parameters are: name_creds_file, credential_id

/home/yet/.pyenv/versions/3.6.7/envs/yet_pyenv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [4]:
################################ Specify dataname and start log
dataname = 'clean_entities'
creds = load_creds_file('/home/yet/credentials_ty.yaml')
log_filename = dataname + "_logfile_run.log"
logging.basicConfig(level=logging.INFO, filename = log_filename)
logger = logging.getLogger(__name__)

loaded yaml file to use

In [33]:
### set up database connection
cursor, psy_connect, alchemy_connection = startengine_alchemy(creds = creds, return_raw_connection = True)

In [7]:
### get feature list
features_static = pd.DataFrame(get_colnames_fromtable_postgres(schema_name = creds['schema_staging'], 
                                table_name = 'entities_address_level_rentstabilized_preclean', 
                                cursor = cursor))

In [9]:
### read table
################################ Read in table and apply renaming dictionary
df_address = readtable_postgres(tablename = 'entities_address_level_rentstabilized_preclean',
                              schemaname = creds['schema_staging'],
                               alchemy_connection = alchemy_connection)

In [10]:
### create table
create_table(cursor, psy_connect, alchemy_connection, 
            tablename = 'entities_XXX', schemaname = creds['schema_staging'], 
            df = df_address_renamed, create_col_dict = create_col_dict)

,address_id,internal_address_name,internal_street_number,internal_street_name,internal_zip,internal_city,internal_county,internal_borough_queens,internal_borough_brooklyn,internal_borough_statenisland,...,pluto_unitsres,pluto_numbldgs,pluto_numfloors,pluto_bldgclass,pluto_assesstot,pluto_yearbuilt,pluto_yearalter1,pluto_yearalter2,subsidized_housing_flag,rent_stabilized_change_2007_2016
0,a0Ft0000002a003EAA,"307, EAST TREMONT AVENUE, BRONX, NY, 10457",307,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,60,1,6.0,C7,1716300,1925,0,0,0,NaN
1,a0Ft0000002a004EAA,"3080, EAST TREMONT AVENUE, BRONX, NY, 10461",3080,EAST TREMONT AVENUE,10461,BRONX,5,0,0,0,...,27,1,3.0,C9,422550,1962,0,0,0,NaN
2,a0Ft0000002a03TEAQ,"3707, EAST TREMONT AVENUE, BRONX, NY, 10465",3707,EAST TREMONT AVENUE,10465,BRONX,5,0,0,0,...,7,2,4.0,C7,194226,1931,0,0,0,NaN
3,a0Ft0000002a07HEAQ,"465, EAST TREMONT AVENUE, BRONX, NY, 10457",465,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,26,1,5.0,C7,492750,1931,1993,0,1,NaN
4,a0Ft0000002a082EAA,"56, EAST TREMONT AVENUE, BRONX, NY, 10453",56,EAST TREMONT AVENUE,10453,BRONX,5,0,0,0,...,24,1,5.0,C7,366300,1923,1992,0,1,NaN
5,a0Ft0000002a08SEAQ,"64, EAST TREMONT AVENUE, BRONX, NY, 10453",64,EAST TREMONT AVENUE,10453,BRONX,5,0,0,0,...,26,1,5.0,C1,709650,1912,2009,2008,1,NaN
6,a0Ft0000002a08XEAQ,"66, EAST TREMONT AVENUE, BRONX, NY, 10453",66,EAST TREMONT AVENUE,10453,BRONX,5,0,0,0,...,0,5,1.0,G1,137250,1931,0,0,0,NaN
7,a0Ft0000002a09BEAQ,"744, EAST TREMONT AVENUE, BRONX, NY, 10457",744,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,17,1,5.0,C7,317250,1931,0,0,0,NaN
8,a0Ft0000002a09EEAQ,"748, EAST TREMONT AVENUE, BRONX, NY, 10457",748,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,17,1,5.0,C7,266850,1931,0,0,0,NaN
9,a0Ft0000002a09yEAA,"868, EAST TREMONT AVENUE, BRONX, NY, 10460",868,EAST TREMONT AVENUE,10460,BRONX,5,0,0,0,...,22,1,5.0,C7,636300,1911,0,0,0,NaN
10,a0Ft0000002a0AcEAI,"19, EAST VAN CORTLANDT AVENUE, BRONX, NY, 10468",19,EAST VAN CORTLANDT AVENUE,10468,BRONX,5,0,0,0,...,43,1,6.0,D1,862200,1932,0,0,0,NaN
11,a0Ft0000002a0AjEAI,"1663, EASTBURN AVENUE, BRONX, NY, 10457",1663,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,43,1,6.0,D1,813150,1928,0,0,1,NaN
12,a0Ft0000002a0AoEAI,"1691, EASTBURN AVENUE, BRONX, NY, 10457",1691,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,36,1,6.0,D1,594450,1937,0,0,0,NaN
13,a0Ft0000002a0ApEAI,"1701, EASTBURN AVENUE, BRONX, NY, 10457",1701,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,48,1,5.0,C7,1236600,1923,0,0,0,NaN
14,a0Ft0000002a0AtEAI,"1745, EASTBURN AVENUE, BRONX, NY, 10457",1745,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,38,1,5.0,C1,556650,1928,2010,0,0,NaN
15,a0Ft0000002a0AyEAI,"1755, EASTBURN AVENUE, BRONX, NY, 10457",1755,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,27,1,5.0,C1,425250,1927,0,0,0,NaN
16,a0Ft0000002a0AzEAI,"1758, EASTBURN AVENUE, BRONX, NY, 10457",1758,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,46,1,5.0,C1,851850,1927,0,0,0,NaN
17,a0Ft0000002a0B0EAI,"1761, EASTBURN AVENUE, BRONX, NY, 10457",1761,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,27,1,5.0,C1,517500,1926,0,0,0,NaN
18,a0Ft0000002a0B3EAI,"1769, EASTBURN AVENUE, BRONX, NY, 10457",1769,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,26,1,5.0,C1,450450,1926,0,0,0,NaN
19,a0Ft0000002a0B4EAI,"1774, EASTBURN AVENUE, BRONX, NY, 10457",1774,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,41,1,6.0,C1,700650,1926,0,0,0,NaN
20,a0Ft0000002a0B5EAI,"1775, EASTBURN AVENUE, BRONX, NY, 10457",1775,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,27,1,5.0,C1,466200,1926,0,0,0,NaN
21,a0Ft0000002a0B6EAI,"1780, EASTBURN AVENUE, BRONX, NY, 10457",1780,EASTBURN AVENUE,10457,BRONX,5,0,0,0,...,37,1,6.0,D1,815400,1941,0,0,0,NaN
22,a0Ft0000002a0C6EAI,"2100, EASTCHESTER ROAD, BRONX, NY, 10461",2100,EASTCHESTER ROAD,10461,BRONX,5,0,0,0,...,70,1,6.0,D1,2248200,1963,0,0,0,NaN
23,a0Ft0000002a0GbEAI,"3463, EASTCHESTER ROAD, BRONX, NY, 10469",3463,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,326,19,6.0,D1,7470000,1935,2004,0,1,NaN
24,a0Ft0000002a0GeEAI,"3467, EASTCHESTER ROAD, BRONX, NY, 10469",3467,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,326,19,6.0,D1,7470000,1935,2004,0,1,NaN
25,a0Ft0000002a0GjEAI,"3485, EASTCHESTER ROAD, BRONX, NY, 10469",3485,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,326,19,6.0,D1,7470000,1935,2004,0,1,NaN
26,a0Ft0000002a0GNEAY,"3436, EASTCHESTER ROAD, BRONX, NY, 10469",3436,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,3,1,3.0,C0,37015,2002,0,0,0,NaN
27,a0Ft0000002a0GOEAY,"3437, EASTCHESTER ROAD, BRONX, NY, 10469",3437,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,326,19,6.0,D1,7470000,1935,2004,0,1,NaN
28,a0Ft0000002a0GPEAY,"3438, EASTCHESTER ROAD, BRONX, NY, 10469",3438,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,3,1,3.0,C0,36000,2002,0,0,0,NaN
29,a0Ft0000002a0GQEAY,"3440, EASTCHESTER ROAD, BRONX, NY, 10469",3440,EASTCHESTER ROAD,10469,BRONX,5,0,0,0,...,3,1,3.0,C0,36060,2002,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45292,a0Ft0000002ZzvrEAC,"1181, EAST TREMONT AVENUE, BRONX, NY, 10460",1181,EAST TREMONT AVENUE,10460,BRONX,5,0,0,0,...,53,2,5.0,C7,1180800,1927,0,0,0,NaN
45293,a0Ft0000002ZzVYEA0,"751, EAST 237 STREET, BRONX, NY, 10466",751,EAST 237 STREET,10466,BRONX,5,0,0,0,...,27,1,5.0,C1,305550,1931,0,0,0,NaN
45294,a0Ft0000002Zzw2EAC,"1230, EAST TREMONT AVENUE, BRONX, NY, 10460",1230,EAST TREMONT AVENUE,10460,BRONX,5,0,0,0,...,60,1,6.0,D1,1255500,1932,1995,0,0,NaN
45295,a0Ft0000002ZzWDEA0,"205, EAST 238 STREET, BRONX, NY, 10470",205,EAST 238 STREET,10470,BRONX,5,0,0,0,...,49,1,6.0,D4,968400,1954,0,0,0,NaN
45296,a0Ft0000002ZzwpEAC,"1936, EAST TREMONT AVENUE, BRONX, NY, 10462",1936,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45297,a0Ft0000002ZzwqEAC,"1938, EAST TREMONT AVENUE, BRONX, NY, 10462",1938,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45298,a0Ft0000002ZzwrEAC,"1940, EAST TREMONT AVENUE, BRONX, NY, 10462",1940,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45299,a0Ft0000002ZzwsEAC,"1946, EAST TREMONT AVENUE, BRONX, NY, 10462",1946,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45300,a0Ft0000002ZzwvEAC,"1960, EAST TREMONT AVENUE, BRONX, NY, 10462",1960,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45301,a0Ft0000002ZzwwEAC,"1970, EAST TREMONT AVENUE, BRONX, NY, 10462",1970,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45302,a0Ft0000002Zzx5EAC,"2090, EAST TREMONT AVENUE, BRONX, NY, 10462",2090,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45303,a0Ft0000002Zzx7EAC,"2100, EAST TREMONT AVENUE, BRONX, NY, 10462",2100,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45304,a0Ft0000002ZzxAEAS,"2120, EAST TREMONT AVENUE, BRONX, NY, 10462",2120,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45305,a0Ft0000002ZzxCEAS,"2130, EAST TREMONT AVENUE, BRONX, NY, 10462",2130,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45306,a0Ft0000002ZzxEEAS,"2140, EAST TREMONT AVENUE, BRONX, NY, 10462",2140,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45307,a0Ft0000002ZzxfEAC,"240, EAST TREMONT AVENUE, BRONX, NY, 10457",240,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,6,1,4.0,S5,136234,1908,0,0,0,NaN
45308,a0Ft0000002ZzxFEAS,"2150, EAST TREMONT AVENUE, BRONX, NY, 10462",2150,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45309,a0Ft0000002ZzxHEAS,"2160, EAST TREMONT AVENUE, BRONX, NY, 10462",2160,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45310,a0Ft0000002ZzxLEAS,"220, EAST TREMONT AVENUE, BRONX, NY, 10457",220,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,10,1,5.0,C1,140745,1931,0,0,0,NaN
45311,a0Ft0000002ZzxMEAS,"2200, EAST TREMONT AVENUE, BRONX, NY, 10462",2200,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45312,a0Ft0000002ZzxQEAS,"2220, EAST TREMONT AVENUE, BRONX, NY, 10462",2220,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45313,a0Ft0000002ZzxsEAC,"242, EAST TREMONT AVENUE, BRONX, NY, 10457",242,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,8,1,4.0,C1,117462,1908,0,0,0,NaN
45314,a0Ft0000002ZzxSEAS,"2240, EAST TREMONT AVENUE, BRONX, NY, 10462",2240,EAST TREMONT AVENUE,10462,BRONX,5,0,0,0,...,3857,54,8.0,R4,97125770,1940,0,0,1,NaN
45315,a0Ft0000002ZzxWEAS,"228, EAST TREMONT AVENUE, BRONX, NY, 10457",228,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,10,1,5.0,C1,156049,1931,0,0,0,NaN
45316,a0Ft0000002ZzYcEAK,"278, EAST 239 STREET, BRONX, NY, 10470",278,EAST 239 STREET,10470,BRONX,5,0,0,0,...,45,2,6.0,D6,1207350,1928,2001,0,0,NaN
45317,a0Ft0000002ZzYeEAK,"305, EAST 239 STREET, BRONX, NY, 10470",305,EAST 239 STREET,10470,BRONX,5,0,0,0,...,57,1,5.0,C7,1597950,1927,2000,2015,0,NaN
45318,a0Ft0000002ZzYZEA0,"273, EAST 239 STREET, BRONX, NY, 10470",273,EAST 239 STREET,10470,BRONX,5,0,0,0,...,49,1,4.0,C1,820800,1931,0,0,0,NaN
45319,a0Ft0000002ZzyzEAC,"259, EAST TREMONT AVENUE, BRONX, NY, 10457",259,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,11,1,5.0,C7,145350,1913,0,0,0,NaN
45320,a0Ft0000002Zzz7EAC,"263, EAST TREMONT AVENUE, BRONX, NY, 10457",263,EAST TREMONT AVENUE,10457,BRONX,5,0,0,0,...,14,1,5.0,C7,402300,1905,1997,0,1,NaN
45321,a0Ft0000002ZzzwEAC,"3050, EAST TREMONT AVENUE, BRONX, NY, 10461",3050,EAST TREMONT AVENUE,10461,BRONX,5,0,0,0,...,7,1,3.0,C1,106960,1928,0,0,0,NaN

In [12]:
### query table
readquery_todf_postgres(query='''select * from dssg_clean.targeted_address limit 10''', alchemy_connection=alchemy_connection)

,id,name,street_number__c,street__c,zip__c,city__c,countyfp__c,borough__c,longitude__c,latitude__c,...,school_district__c,census_block_group__c,census_block__c,census_tract__c,community_district__c,congressional_district__c,council_district__c,assembly_district__c,units,bldg_wide
0,a0Ft0000002ZqGdEAK,"1020, ANDERSON AVENUE, BRONX, NY, 10452",1020,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.926605,40.832703,...,9,360050189002,360050189002001,36005018900,204,15,8,77,1,None
1,a0Ft0000002ZqGiEAK,"1050, ANDERSON AVENUE, BRONX, NY, 10452",1050,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.926162,40.833406,...,9,360050193001,360050193001002,36005019300,204,15,8,77,65,None
2,a0Ft0000002ZqGmEAK,"1055, ANDERSON AVENUE, BRONX, NY, 10452",1055,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.926124,40.833883,...,9,360050193001,360050193001001,36005019300,204,15,8,77,4,None
3,a0Ft0000002ZqGyEAK,"1092, ANDERSON AVENUE, BRONX, NY, 10452",1092,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.925294,40.834539,...,9,360050193001,360050193001000,36005019300,204,15,8,77,20,None
4,a0Ft0000002ZqH4EAK,"1122, ANDERSON AVENUE, BRONX, NY, 10452",1122,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.924830,40.835097,...,9,360050199002,360050199002001,36005019900,204,15,16,84,4,None
5,a0Ft0000002ZqHOEA0,"900, ANDERSON AVENUE, BRONX, NY, 10452",900,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.928492,40.830267,...,9,360050189002,360050189002001,36005018900,204,15,8,77,1,None
6,a0Ft0000002ZqHPEA0,"901, ANDERSON AVENUE, BRONX, NY, 10452",901,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.928496,40.830569,...,9,360050189003,360050189003004,36005018900,204,15,8,84,43,None
7,a0Ft0000002ZqHREA0,"950, ANDERSON AVENUE, BRONX, NY, 10452",950,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.928008,40.830936,...,9,360050189002,360050189002001,36005018900,204,15,8,77,5,None
8,a0Ft0000002ZqHTEA0,"952, ANDERSON AVENUE, BRONX, NY, 10452",952,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.927921,40.831099,...,9,360050189002,360050189002001,36005018900,204,15,8,77,5,None
9,a0Ft0000002ZqHUEA0,"953, ANDERSON AVENUE, BRONX, NY, 10452",953,ANDERSON AVENUE,10452,BRONX,5,Bronx,-73.927960,40.831247,...,9,360050189003,360050189003000,36005018900,204,15,8,84,38,None

In [ ]:
### insert
cursor.execute(query='''''')

In [34]:

def sql_insert_function(schematable_insert,columns_to_insert,values_to_insert,
                       alchemy_connection):
    ### insert query
    if schematable_insert == 'dssg_results.model_group' or schematable_insert == 'dssg_results.models':
        insert_table_query = """
                        INSERT INTO {schematable_insert} ({columns_to_insert}) values
                        ({values_to_insert})
                        """.format(schematable_insert = schematable_insert,
                                   columns_to_insert = columns_to_insert,
                                   values_to_insert = values_to_insert
                                  )
    else:
        insert_table_query = """
                INSERT INTO {schematable_insert} values
                ({values_to_insert})
                """.format(schematable_insert = schematable_insert,
                           values_to_insert = values_to_insert
                          )
    ### execute query
    alchemy_connection.execute(sqlalchemy.text(insert_table_query))
    
    return None

In [35]:
sql_insert_function(schematable_insert='dssg_results.model_group',
                    columns_to_insert= 'algorithm_type,label,hyperparameters,\
                    feature_list,borough,model_group_comment',
                    values_to_insert="'test1','test','test','test','test','test'",
                   alchemy_connection = alchemy_connection)